# Generated by Django 4.0.4 on 2022-05-19 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tokio_authors_myhokku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myhokku',
            name='author',
        ),
    ]
