# Generated by Django 4.0.4 on 2022-05-19 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_project'),
        ('blog', '0003_remove_myhokku_author'),
    ]

    operations = [
    ]
