# Generated by Django 4.0.4 on 2022-05-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_merge_0002_project_0003_remove_myhokku_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('subject', models.TextField()),
            ],
        ),
    ]
